/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function addComponent(args: CreateComponentArgs): Key

export declare function addWire(circuitKey: Key, wire: TransientWireState): void

/** Creates a new circuit and returns its key as an i64 for JS. */
export declare function createCircuit(name: string): Key

export interface CreateComponentArgs {
  circuitKey: Key
  componentType: string
  label?: string
  labelOrientation?: number
  x: number
  y: number
  bitsize?: number
  inputs?: number
  orientation?: number
  constantValue?: string
  isInput?: boolean
  selsize?: number
  textContent?: string
  handedness?: number
}

/** Function Get Transient State, gets the relevant data and state of all components in a circuit */
export declare function getTransientState(circuitKey: Key): [Array<TransientComponentState>, Array<TransientWireState>]

export interface Key {
  kind: KeyKind
  id: [number, number]
}

export declare const enum KeyKind {
  Circuit = 'Circuit',
  Function = 'Function',
  UI = 'UI'
}

export interface Location {
  x: number
  y: number
}

export interface PortTransientState {
  x: number
  y: number
  value: string
  issues: Array<string>
}

export declare function printCircuit(circuitKey: Key): string

export declare function propagate(circuitKey: Key): void

export declare function removeComponent(circuitKey: Key, componentKey: Key): void

export interface TransientComponentState {
  backendKey: Key
  ports: Array<PortTransientState>
  bounds: Array<Location>
  componentValue?: string
}

export interface TransientWireState {
  endpoints: Array<Location>
  isHorizontal: boolean
  length: number
  value: string
  issues: Array<string>
}
