/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function addComponent(args: CreateComponentArgs): Key

/** Tries to add the wire to the circuit, returning whether it was successful. */
export declare function addWire(circuitKey: Key, start: Location, end: Location): boolean

/** Creates a new circuit and returns its key as an i64 for JS. */
export declare function createCircuit(name: string): Key

export interface CreateComponentArgs {
  circuitKey: Key
  componentType: string
  label?: string
  labelOrientation?: Orientation
  pos: Location
  bitsize?: number
  inputs?: number
  orientation?: Orientation
  constantValue?: string
  isInput?: boolean
  selsize?: number
  textContent?: string
  handedness?: Handedness
}

/** Function Get Transient State, gets the relevant data and state of all components in a circuit */
export declare function getTransientState(circuitKey: Key): [Array<TransientComponentState>, Array<TransientWireState>]

export type Handedness =  'TopLeft'|
'DownRight';

export interface Key {
  kind: KeyKind
  id: [number, number]
  __v_skip: boolean
}

export type KeyKind =  'Circuit'|
'Function'|
'UI';

export interface Location {
  x: number
  y: number
}

export type Orientation =  'North'|
'South'|
'East'|
'West';

export interface PortTransientState {
  pos: Location
  value: string
  issues: Array<string>
}

export declare function printCircuit(circuitKey: Key): string

export declare function propagate(circuitKey: Key): void

export declare function removeComponent(circuitKey: Key, componentKey: Key): void

/** Tries to remove the wire from the circuit, returning whether it was successful. */
export declare function removeWire(circuitKey: Key, start: Location, end: Location): boolean

export interface TransientComponentState {
  backendKey: Key
  ports: Array<PortTransientState>
  bounds: [Location, Location]
}

export interface TransientWireState {
  endpoints: [Location, Location]
  value: string
  issues: Array<string>
}
